modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="coffeecraft"
version="1.0.0"
displayName="CoffeeCraft"
displayURL="https://autheman-victor.fr"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Victor Autheman, Rémi Bregeard"

[[dependencies.coffeecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.coffeecraft]]
    modId="patchouli"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.coffeecraft]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.coffeecraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.coffeecraft]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

